# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.ManyToManyField(to='categories.Category', verbose_name='интересные категории'),
        ),
    ]
