# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='', verbose_name='описание события'),
        ),
    ]
